### PR TITLE
SLING-9558 - Fix broken --install option in Composum upload command.

### PR DESCRIPTION
**Pull request by hsaginor**

### CODE REVIEW

**Comment by rombert** [comment]
@hsaginor  - can you please file a Jira for this?

**Comment by hsaginor** [comment]
@rombert 
https://issues.apache.org/jira/browse/SLING-9558

**Comment by rombert** [comment]
Thanks @hsaginor ! Can you please update the commit title as well and re-push the changes? I guess 6cd2703 should be updated. See https://sling.apache.org/contributing.html#git for details

**Comment by hsaginor** [comment]
@rombert Thank you! I hope I did it correctly this time. :)

**Comment by rombert** [comment]
It's perfect @hsaginor :-)

Thanks!

**Pull request merged**
